"""The INVITE transaction state machines (RFC 3261 §17).

A SIP transaction sits between the wire and the transaction user (TU). The two
that need explicit handling for an INVITE are:

* :class:`InviteClientTransaction` (§17.1.1) — for an INVITE **we** send. Its
  load-bearing job here is the **ACK for a non-2xx final response** (§17.1.1.3):
  that ACK is generated by the client transaction, on the **same branch** as the
  INVITE, and is emphatically *not* the TU's job (the TU emits only the
  §13.2.2.4 ACK to a **2xx**, in a fresh transaction). In the ``Completed`` state
  the transaction re-emits that same ACK for every retransmitted final response,
  absorbing the retransmission.
* :class:`InviteServerTransaction` (§17.2.1) — for an INVITE we receive. It
  tracks the final response and **absorbs** the peer's ACK so a retransmitted ACK
  is not mistaken for a new request.

This module is **sans-IO**: it consumes parsed messages and returns wire text /
state, never touching a socket. Over a reliable transport (TLS) the request
retransmission timers (Timer A / Timer E) are disabled — there is nothing to
retransmit — so the states are modelled but the timer-driven resends are not
armed; the response-side absorption and the ACK generation are transport-agnostic
and always apply.
"""

from __future__ import annotations

from enum import Enum, auto

from hermes_voip.message import SipRequest, SipResponse, build_request

__all__ = [
    "InviteClientTransaction",
    "InviteServerTransaction",
    "TransactionState",
]

_PROVISIONAL_CEILING = 200  # status < 200 is provisional (1xx)
_FIRST_FAILURE = 300  # status >= 300 is a non-2xx final (4xx/5xx/6xx, plus 3xx)
_MAX_FORWARDS = "70"


class TransactionState(Enum):
    """The RFC 3261 §17 INVITE transaction states relevant to this layer."""

    CALLING = auto()  # client: request sent, no response yet (§17.1.1.2)
    PROCEEDING = auto()  # a provisional (1xx) has been seen
    COMPLETED = auto()  # a non-2xx final seen; ACK generated and re-sent on resend
    TERMINATED = auto()  # 2xx final (client) or done (server)


class InviteClientTransaction:
    """Client INVITE transaction: generates the non-2xx ACK (RFC 3261 §17.1.1)."""

    def __init__(self, invite_text: str) -> None:
        """Bind the transaction to the INVITE wire text it represents.

        Args:
            invite_text: The full INVITE request as sent on the wire.

        Raises:
            ValueError: if ``invite_text`` is not a parseable INVITE request, or
                lacks a header the ACK must echo (Via/From/To/Call-ID/CSeq).
        """
        invite = SipRequest.parse(invite_text)
        if invite.method != "INVITE":
            msg = f"not an INVITE request: {invite.method}"
            raise ValueError(msg)
        self._invite = invite
        self._state = TransactionState.CALLING
        self._ack: str | None = None

    @property
    def state(self) -> TransactionState:
        """The current transaction state."""
        return self._state

    def ack_for_response(self, response: SipResponse) -> str | None:
        """Feed a response; return the ACK wire text iff this layer must send it.

        A **non-2xx final** (status >= 300) yields the §17.1.1.3 ACK and moves the
        transaction to ``Completed``; a retransmitted final re-emits the same ACK
        (absorbing the retransmission). A **2xx** yields ``None`` and terminates
        the transaction — the TU ACKs the 2xx itself (§13.2.2.4). A provisional
        (1xx) yields ``None`` and moves to ``Proceeding``.
        """
        status = response.status_code
        if status < _PROVISIONAL_CEILING:
            if self._state is TransactionState.CALLING:
                self._state = TransactionState.PROCEEDING
            return None
        if status < _FIRST_FAILURE:
            # 2xx: the TU owns this ACK (fresh transaction); we are done.
            self._state = TransactionState.TERMINATED
            return None
        # Non-2xx final: build the ACK once, then re-emit it on retransmissions.
        if self._ack is None:
            self._ack = self._build_ack(response)
        self._state = TransactionState.COMPLETED
        return self._ack

    def _build_ack(self, response: SipResponse) -> str:
        """Construct the §17.1.1.3 ACK for a non-2xx final response.

        Request-URI, Call-ID, From and the single top Via (same branch) come from
        the INVITE; the To (with the server's tag) comes from the response; the
        CSeq number is the INVITE's with method ``ACK``. Any INVITE ``Route``
        headers are repeated so the ACK follows the same path.
        """
        headers: list[tuple[str, str]] = [
            ("Via", _require(self._invite, "Via")),
            ("Max-Forwards", _MAX_FORWARDS),
        ]
        headers += [("Route", route) for route in self._invite.headers_all("Route")]
        headers += [
            ("From", _require(self._invite, "From")),
            ("To", _require(response, "To")),
            ("Call-ID", _require(self._invite, "Call-ID")),
            ("CSeq", f"{_cseq_number(_require(self._invite, 'CSeq'))} ACK"),
        ]
        return build_request("ACK", self._invite.request_uri, headers)


class InviteServerTransaction:
    """Server INVITE transaction: tracks our final response and absorbs the ACK.

    For an INVITE we received and answered, the peer's client transaction sends
    the ACK to our non-2xx final (we never generate it). This transaction records
    the final status and absorbs the inbound ACK so a retransmitted ACK is not
    surfaced to the TU as a fresh request (RFC 3261 §17.2.1).

    Over the reliable TLS transport the connection layer does not arm this
    transaction's response-retransmission timer: an inbound ACK arrives as an
    in-dialog request and is consumed by the dialog layer's ``handle_request``
    (method ``ACK``). The class is the §17.2 state model — exercised directly by
    its unit tests — kept for the UDP-capable transport and for an explicit,
    correct server-side state machine.
    """

    def __init__(self) -> None:
        """Start in the ``Proceeding`` state (the INVITE has been received)."""
        self._state = TransactionState.PROCEEDING

    @property
    def state(self) -> TransactionState:
        """The current transaction state."""
        return self._state

    def on_final_sent(self, status_code: int) -> None:
        """Record that we sent a final response of ``status_code``.

        A non-2xx final (>= 300) moves to ``Completed`` (await the ACK); a 2xx
        terminates the transaction — the 2xx ACK arrives end-to-end in a fresh
        transaction, not absorbed here (§17.2.1 / §13.3.1.4).

        Raises:
            ValueError: if ``status_code`` is provisional (a final is required).
        """
        if status_code < _PROVISIONAL_CEILING:
            msg = f"on_final_sent requires a final status, got {status_code}"
            raise ValueError(msg)
        self._state = (
            TransactionState.COMPLETED
            if status_code >= _FIRST_FAILURE
            else TransactionState.TERMINATED
        )

    def absorb_ack(self) -> bool:
        """Absorb an inbound ACK to our non-2xx final; return whether it was ours.

        Returns ``True`` (and moves to ``Confirmed``/``Terminated``) when an ACK
        is expected for our non-2xx final; ``False`` if no non-2xx final is
        outstanding (the ACK is not for this transaction).
        """
        if self._state is TransactionState.COMPLETED:
            self._state = TransactionState.TERMINATED
            return True
        return False


def _require(message: SipRequest | SipResponse, name: str) -> str:
    value = message.header(name)
    if value is None:
        msg = f"message has no {name} header"
        raise ValueError(msg)
    return value


def _cseq_number(cseq: str) -> int:
    parts = cseq.split()
    if not parts or not parts[0].isdigit():
        msg = f"malformed CSeq: {cseq!r}"
        raise ValueError(msg)
    return int(parts[0])
